---
  - name: Update the distro
    apt: upgrade=yes update_cache=yes cache_valid_time=3600

  - name: Install packages
    apt: pkg={{ item }} state=installed
    with_items: 
      - "{{ common_packages }}"

  - name: Install VIM as default text editor
    alternatives: name=editor path=/usr/bin/vim.basic
    when: "'vim' in common_packages"

  - include: deployer.yml
    when: common_manage_deployer

  - include: hostname.yml
  - include: timezone.yml
  - include: ssh.yml
  - include: ntp.yml
  - include: motd.yml
