#!/bin/bash

set -ev

pushd tests

ansible-playbook test.yml --syntax-check
ansible-playbook test.yml --connection=local --sudo
ansible-playbook test.yml --connection=local --sudo \
    | grep -q 'changed=0.*failed=0' \
    && (echo 'Idempotence test: pass' && exit 0) \
    || (echo 'Idempotence test: fail' && exit 1)

popd
